[ingot]
name = "solidity"
version = "0.0.1"

[dependencies]
legacy_std = { path = "../legacy_std", version = "0.0.1" }
map = { path = "../map", version = "0.0.1" }
evm = { path = "../evm", version = "0.0.1" }
